### ISSUE TITLE
"frame dropped!" and "No attribute or service found with name 'AVTransport'" errors

### ISSUE THREAD

**Issue by Vunse** [link89/dlna-cast#1]
I only get a bunch of errors like this one:

_real-time buffer [screen-capture-recorder] [video input] too full or near too full (464% of size: 3041280 [rtbufsize parameter])! frame dropped!_

After ~3 seconds of errors the program breaks:

_AttributeError: No attribute or service found with name 'AVTransport'._

Is there any fix for this?

**Comment by link89** [comment]
```
real-time buffer [screen-capture-recorder] [video input] too full or near too full (464% of size: 3041280 [rtbufsize parameter])! frame dropped!
```
Means the ffmpeg capure speed is behind the framerate. It may have something to do with the performace of your hardware.
